### ISSUE TITLE
does not work since version 1.2.1-25

### ISSUE THREAD

**Issue by shinjitsunokami** [stangri/luci-app-pbr#11]
The issue started with version `1.2.1-25`, but rolling back to version `1.2.1-23` works fine.

<img width="2395" height="1214" alt="Image" src="https://github.com/user-attachments/assets/9bd36208-7276-48dd-ab67-3ccf58de665e" />

**Comment by lopez5743** [comment]
Problem fixed with 1.2.1 r31

**Comment by shinjitsunokami** [comment]
The issue is still occurring on r31. @@

<img width="1380" height="1372" alt="Image" src="https://github.com/user-attachments/assets/efa7b7e1-e8f1-4bab-8f44-015ad5f36481" />

**Comment by stangri** [comment]
@shinjitsunokami csn you please try rebooting the router?

**Comment by shinjitsunokami** [comment]
> [@shinjitsunokami](https://github.com/shinjitsunokami) csn you please try rebooting the router?

@stangri Thanks for your prompt response. I’ve rebooted the router several times, but the issue is still there.
Even flashing new firmware built by [openwrt/imagebuilder](https://openwrt.org/docs/guide-user/additional-software/imagebuilder) (added your repo) didn’t resolve it :(

Tested on [Cudy TR3000](https://openwrt.org/toh/cudy/tr3000) and FriendlyElec NanoPi R6S

**Comment by shinjitsunokami** [comment]
@stangri @lopez5743 Sorry, it seems the issue is still happening due to the browser's cache.
Accessing from another device, using incognito mode, or clearing the browser's data resolved the issue on [1.2.1 r31](https://github.com/stangri/luci-app-pbr/releases/tag/v1.2.1-31)
